config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  post 'products/index'
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :destroy
    validates :discount, inclusion: {in: 0..100}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  scope :premium, ->{where(premium: true)}
  scope :last_n, ->(num) {limit(num)}

  after_destroy :last_product

  def last_product
    Category.all.each do |category|
      if category.products.empty?
        category.destroy
      end
    end
  end

  def precio_final
    disc = self.category.discount
    pric = self.price

    descuento = (pric * disc.to_f)/100
    return pric - descuento
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    if params[:buscador].present?
      if params[:filtro_precio].present?
        @products = Product.where("name like ?", "%#{params[:buscador]}%")
        if params[:filtro_precio] == "0..5000"
          @products = Product.where("name like ? and price BETWEEN ? AND ?", "%#{params[:buscador]}%", 0, 5000)
        elsif params[:filtro_precio] == "5001..10000"
          @products = Product.where("name like ? and price BETWEEN ? AND ?", "%#{params[:buscador]}%", 5001, 10000)
        elsif params[:filtro_precio] == "10001..+"
          @products = Product.where("name like ? and price >= ?", "%#{params[:buscador]}%", 10001)
        end
      end
    else
      @products = Product.all
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css" rel="stylesheet" integrity="sha384-pVJelSCJ58Og1XDc2E95RVYHZDPb9AVyXsI8NoVpB2xmtxoZKJePbMfE4mlXw7BJ" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="#">Link<span class="sr-only">(current)</span></a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="row form-horizontal">
  <fieldset>
    <legend>Buscar</legend>
    <%= form_tag(products_index_path) do %>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Buscardor</label>
      <div class="col-lg-8">
        <%= text_field_tag :buscador, nil, placeholder: "Buscar nombre", class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Filtro Precio</label>
      <div class="col-lg-8">
        <%= select_tag :filtro_precio, options_for_select([ "Todos","0..5000", "5001..10000", "10001..+" ], "Todos"), class:"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= submit_tag "Buscar", class:"btn btn-primary" %>
      </div>
    </div>
  </fieldset>
  <% end -%>
</div>
<br>
<br>
<div class="row form-horizontal">
  <fieldset>
    <legend>Buscar</legend>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Prince</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.category.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>
</div>